version: '3.8'
services:
  sistema_wo:
    build:
      context: ./
      target: runner
    container_name: medlopes_wo
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mysql
    command: >
      sh -c "npm install && npm run dev"

  mysql:
    image: mysql:8.0
    container_name: mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
