export class ProductionBudgetUtils {
	static endProducts = [
		'Avental',
		'Babete Adulto',
		'Bata',
		'Bata Mehak',
		'Bata Rainha',
		'Blazer Feminino',
		'Blazer Masculino',
		'Blusa',
		'Blusa Dourada',
		'Blusa Kimora',
		'Bubu',
		'Calça',
		'Calça Boyfriend',
		'Calça Feminina',
		'Calça Feminina Panta',
		'Calça Rose',
		'Calça Social Feminina',
		'Calça Social Infantil',
		'Calça Social Masculina',
		'Calção Feminino',
		'Calção Masculino',
		'Camisa',
		'Camisa Bubu',
		'Camisa Feminina',
		'Camisa Manga Curta',
		'Camisa Masculina',
		'Casaco',
		'Chapéu',
		'Cinto',
		'Colete',
		'Conjunto Feminino',
		'Conjunto Masculino',
		'Corpete',
		'Fato Social Feminino',
		'Fato Social Masculino',
		'Fita',
		'Gravata',
		'Guardanapos',
		'Jaleca',
		'Jaqueta Bomber',
		'Kimono',
		'Laço de Vestido',
		'Macação',
		'Macação Curto',
		'Macação Ende',
		'Macação Fiesta',
		'Macação Longo',
		'Macação Mango',
		'Máscara',
		'Pantalona',
		'Pantalona Safari',
		'Saia Curta',
		'Saia Kianda',
		'Saia Lápis',
		'Saia Longa',
		'Saia Night',
		'Saia Tropa',
		'Sobre Tudo',
		'Top',
		'Top Borboleta',
		'Top Tânia',
		'Top´s',
		'Túnica',
		'Vestido',
		'Vestido 1 Manga',
		'Vestido Casual',
		'Vestido Curto',
		'Vestido Curto de Gala',
		'Vestido de Gala',
		'Vestido ellen',
		'Vestido Infantil',
		'Vestido Isabela',
		'Vestido Longo'
	]

	static colors = [
		'Amarelo',
		'Amarelo Manteiga',
		'Amarelo Mostarda',
		'Arco Íris',
		'Azul',
		'Azul Bebé',
		'Azul Claro',
		'Azul E branco',
		'Azul Escuro',
		'Azul Lapizeira',
		'Azul Marinho',
		'Azul Royal',
		'Bege',
		'Branca',
		'Branco e Dourado',
		'Camarão',
		'Castanha',
		'Castanho claro',
		'Cinzenta',
		'Creme',
		'Dourada',
		'Estampada',
		'Flores',
		'Laranja',
		'Lilás',
		'Lima',
		'Mostarda',
		'Nude e Lilás',
		'Popline',
		'Preto',
		'Rosa',
		'Rosa Antiga',
		'Rosa Choque',
		'Rosa Pastel',
		'Terra',
		'Verde',
		'Verde Alface',
		'Verde Escuro',
		'Verde Lima',
		'Vermelho',
		'Vinho'
	]
}
