import { Metadata } from 'next'
import { Layout, LayoutBody } from './components'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <Layout>
      <LayoutBody>Ola</LayoutBody>
    </Layout>
  )
}
