export * from './remote-add-insured-factory'
export * from './remote-count-insured-factory'
export * from './remote-delete-insured-factory'
export * from './remote-load-insureds-factory'
export * from './remote-update-insured-factory'
