export interface Employee {
	id: number
	name: string
	gender: string
	dateOfBirth: Date
	maritalStatus: string
	documentType: string
	documentNumber: string
	nif?: string
	socialSecurity?: string
	dependents: number
	educationDegree: string
	phone1: string
	phone2?: string
	email: string
	municipalityId: number
	provinceId?: number
	countyId?: number
	residentialAddress: string
	position: string
	baseSalary?: number
	hireDate: Date
	contractEndDate?: Date
	bankName?: string
	iban?: string
	accountNumber?: string
	createdAt: Date
	createdBy?: number
	updatedAt?: Date
	updatedBy?: number
}
